const creatorLeaderboard = [
  {
    id: 1,
    name: "VideoWhiz",
    platform: "YouTube",
    followers: 15243000,
    engagement: 82,
    change: 14,
  },
  {
    id: 2,
    name: "ContentQueen",
    platform: "Instagram",
    followers: 8965000,
    engagement: 65,
    change: 7,
  },
  {
    id: 3,
    name: "TrendSetter",
    platform: "TikTok",
    followers: 7832000,
    engagement: 59,
    change: -2,
  },
  {
    id: 4,
    name: "PodcastPro",
    platform: "Spotify",
    followers: 6921000,
    engagement: 48,
    change: 9,
  },
  {
    id: 5,
    name: "InfluencerDaily",
    platform: "Instagram",
    followers: 5467000,
    engagement: 41,
    change: 5,
  },
  {
    id: 6,
    name: "StreamKing",
    platform: "Twitch",
    followers: 4832000,
    engagement: 36,
    change: 3,
  },
  {
    id: 7,
    name: "SocialGuru",
    platform: "Twitter",
    followers: 3943000,
    engagement: 32,
    change: -1,
  },
  {
    id: 8,
    name: "ContentCreator",
    platform: "YouTube",
    followers: 3654000,
    engagement: 29,
    change: 0,
  },
  {
    id: 9,
    name: "ReelMaster",
    platform: "Instagram",
    followers: 2987000,
    engagement: 24,
    change: -5,
  },
  {
    id: 10,
    name: "ViralVoice",
    platform: "TikTok",
    followers: 2654000,
    engagement: 18,
    change: 2,
  },
];

export default creatorLeaderboard;
